### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by xdk78** [Bjornskjald/idziennik-electron#2]
Some tips:
- Don't use jquery if you have vue. 
- Why Electron isn't added to dependency in package.json? And few other packages? 
- Add js linter like Eslint

**Comment by ptrcnull** [comment]
jQuery was needed for Materialize.js, I'm currently removing it as it's not needed anymore
Electron wasn't added, because... I didn't know how to do it when I created this project, will fix
I'm already using standard.js, but I haven't added it to package.json

**Comment by ptrcnull** [comment]
But anyway, thanks for the tips, especially for adding Electron as a dependency, because I simply forgot about it

**Comment by xdk78** [comment]
That's better :smile: You can use Vuetify Material Design framework instead Materialize IMO is better.
For example https://github.com/xdk78/librus-client-desktop

**Comment by ptrcnull** [comment]
Actually, I don't think I need Vue anymore, but if I'll have to do a project with Vue then I will use it, thanks!

**Comment by ghost** [comment]
InfernoJS is good too!
